### PR TITLE
Avoid using shared resource streams between class loaders when extracting the native library.

### PR DESCRIPTION
**Pull request by danysantiago**
This changes makes it so that we replace` Class#getResourceAsStream()` with a custom method that finds the resources and creates a stream but disables caching the stream. This is necessary in environments with where the native library has to be extracted and used with multiple class loaders that get closed.

Specifically, I was observing the following [JDK-8205976](https://bugs.openjdk.java.net/browse/JDK-8205976) in a [Gradle](https://gradle.org/) project with concurrent tasks that use sqlite-jdbc. The exact exception I was observing was:
```
java.io.IOException: Stream closed
        at java.base/java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:68)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:143)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
        at org.sqlite.SQLiteJDBCLoader.contentsEquals(SQLiteJDBCLoader.java:179)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:243)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:344)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67)
 ```
 Which lead me to JDK-8205976 after lots of logging. The test is a big complicated but sets ups the exact case for when this occurs. Multiple concurrent threads with isolated class loaders initializing the library for which the resource on all point to the same jar.

### CODE REVIEW

**Review by yigit — COMMENTED** [review]
👍

**Comment by danysantiago** [comment]
Hi @xerial - Sorry to ping you, but is there a chance you can take a look at this PR, would love for it to get merged if possible. Thanks!

**Comment by xerial** [comment]
ok. I'm not aware of this bug https://bugs.openjdk.java.net/browse/JDK-8205976. Let me check

**Comment by danysantiago** [comment]
@xerial, just a friendly ping on this, hope you are well. Thank you!

**Comment by yigit** [comment]
Hi @xerial , sorry for pinging here again, is there any chance of merging this and releasing a new version?
This became a bigger blocker for us AndroidX at this point (due to the adoption of Apple M1).

Let us know if we can help in any way.

**Comment by gauravk95** [comment]
@xerial it would be of great help, if you could merge this pull request. Those with M1 are having a tough time.

**Comment by snitsaruk** [comment]
Can this be merged?

**Comment by xerial** [comment]
Yes. Thanks for waiting. I'll release 3.35.0 soon.

**Pull request merged**
