### PR TITLE
Progress handler

### PR DESCRIPTION
**Pull request by irrelative**
This enables bindings for the query progress functions in Java, as defined:

https://www.sqlite.org/c3ref/progress_handler.html

I removed the concept of the context void pointer, since this passes the java instance itself and it's just an interface. It follows the code style of the user-defined functions wherever possible. Let me know if there are stylistic issues, and any additional feedback is appreciated. I've written a fair amount of C and Java, but rarely combined.

### CODE REVIEW

**Comment by irrelative** [comment]
Test failures appear to be Travis related, specifically not building native. I think this was an issue in the past as well.

This has built for me on OSX and Ubuntu 1404.

**Comment by ElMoe** [comment]
Hi,
Google brought me here - because i was searching if there's a JDBC driver that already implements the SQLite progress handler.
When i look into the error messages all errors result from ProgressHandler.setHandler Line16:  `throw new SQLException("connection closed");`
Are you sure that `conn = DriverManager.getConnection("jdbc:sqlite:");` in ProgressHandlerTest.java
Line 22 is the right connection URL?
Best regards,
Elmoe

**Comment by gitblit** [comment]
@irrelative Could you rebase & squash based on master and reference your new test class in `AllTests`?  Travis should be working now with building native libs.

**Comment by gitblit** [comment]
@mkauf Would you be willing to review this PR, rebase it, and open a new PR?

**Comment by gitblit** [comment]
Moved to PR #134.

**Pull request closed without merging**
