### PR TITLE
fix: throw java.lang.ExceptionInInitializerError when calling SQLiteConfig.Pragma.values()

### PR DESCRIPTION
**Pull request by ianhash**
This pull request fixes the bug described in #1123 .

### CODE REVIEW

**Comment by gotson** [comment]
thanks for the PR.

Can you fix the code formatting with `mvn spotless:apply` ?

**Comment by ianhash** [comment]
> thanks for the PR.
> 
> Can you fix the code formatting with `mvn spotless:apply` ?

DONE

**Comment by gotson** [comment]
the unit tests are using the wrong assertion package

**Comment by ianhash** [comment]
> the unit tests are using the wrong assertion package

FIXED

**Comment by gotson** [comment]
thanks

**Pull request merged**
