### PR TITLE
feat: add riscv64 binaries

### PR DESCRIPTION
**Pull request by qyl27**

### CODE REVIEW

**Comment by gotson** [comment]
some context would help. I see it's using Dockcross, so that seems alright, but why did the windows dll changed?

**Comment by gotson** [comment]
> Oh, the changes to windows dll seem like by the bot, should I revert it?

yes please

> The os info of RISC-V did is `riscv64`, I had a misunderstanding with the `OSInfo` class.

no that's fine, i checked the code and if the `os.info` value is the same as the folder name then the loading should be good.

**Comment by qyl27** [comment]
All done.

**Comment by gotson** [comment]
Thanks for the PR, a good addition to the project!

**Comment by sualeh** [comment]
Also see https://github.com/schemacrawler/SchemaCrawler/discussions/1624

**Pull request merged**
