### PR TITLE
Added detection of the CHAR datatype.

### PR DESCRIPTION
**Pull request by RobertZenz**

### CODE REVIEW

**Comment by gitblit** [comment]
This seems like a good idea.  Can you provide a unit test which demonstrates it's utility?

**Comment by RobertZenz** [comment]
I've added the (at least I hope) appropriate unit test.

**Comment by RobertZenz** [comment]
I've rebased my/this branch on the latest master.

**Comment by gitblit** [comment]
Great, thank you!

**Comment by RobertZenz** [comment]
Pleasure was mine.

**Pull request merged**
