### PR TITLE
Update Makefile, remove outdated precompiled version of OSInfo

### PR DESCRIPTION
**Pull request by Willena**
This is a fix for #714

### CODE REVIEW

**Comment by gotson** [comment]
similar to #691 #697 #698

**Comment by gotson** [comment]
@Willena can you add `.class` to `.gitignore` ? Then it will be good to merge

**Comment by Willena** [comment]
> @Willena can you add `.class` to `.gitignore` ? Then it will be good to merge

No problem, I'll do that next week !

**Comment by Willena** [comment]
@gotson `.class` has been added to `.gitignore`

**Comment by gotson** [comment]
Thanks a lot!

**Pull request merged**
