### PR TITLE
org.sqlite.SQLiteConfig.setDatePrecision(String) throws unnecessary S…

### LINKED ISSUE #467: org.sqlite.SQLiteConfig.setDatePrecision(String) throws unnecessary SQLException
The signature is `public void setDatePrecision(String datePrecision) throws SQLException`, but at no point in the code a `SQLException` is thrown.
This just adds unnecessary boilerplate code. Please remove.

### PR DESCRIPTION
**Pull request by michael-o**
…QLException (#467)

This fixes #467

### CODE REVIEW

**Comment by michael-o** [comment]
@gotson Here you go!

**Review by PromanSEW — COMMENTED** [review]
You should remove @throws Javadoc also

**Comment by michael-o** [comment]
> You should remove @throws Javadoc also

You are totally right. Will do.

**Comment by michael-o** [comment]
@PromanSEW Done

**Pull request merged**
