### PR TITLE
Version bump to 3.25.2 (from 3.23.1)

### PR DESCRIPTION
**Pull request by urzds**
Closes: https://github.com/xerial/sqlite-jdbc/issues/368

Please note that #372 and #373 should be merged first, because they fix build issues that exist independently of this PR.

### CODE REVIEW

**Comment by matpag** [comment]
@xerial Do you think you will have time for this sooner or later? 😁

**Comment by xerial** [comment]
ok. I'll work on releasing a new version.

**Comment by matpag** [comment]
Big thanks @xerial

**Comment by takacsot** [comment]
Great news. Thank you

**Pull request merged**
