### PR TITLE
Upgrade SQLite to 3.37.0

### PR DESCRIPTION
**Pull request by pyckle**
Update dockcross scripts in repository, and add script to make future updates easier
Fix ppc64 dockcross build - cross compile prefix name changed slightly
Update SQLite VERSION to 3.37.0

### CODE REVIEW

**Comment by pyckle** [comment]
All docker cross compiled binaries now build cleanly. I did not include them, but I can if you'd prefer.
I do not have an M1 Mac, so I cannot easily build the Mac aarch binary.

**Comment by gotson** [comment]
Would it be worth splitting the Musl check enhancement in a separate PR?

**Comment by pyckle** [comment]
> Would it be worth splitting the Musl check enhancement in a separate PR?
Done: https://github.com/xerial/sqlite-jdbc/pull/716

**Comment by gotson** [comment]
> > Would it be worth splitting the Musl check enhancement in a separate PR?
> > Done: #716

Thanks, but I see the changes are still part of this PR though.

**Comment by pyckle** [comment]
> Thanks, but I see the changes are still part of this PR though.

Just removed the two referenced commits, and pushed this branch them.

**Comment by tjlee** [comment]
Just wondering, is there any plans to apply PR in nearest future?

**Comment by gotson** [comment]
@pyckle is this worth looking at, or should i look directly at #728 ?

**Comment by pyckle** [comment]
This is outdated. There's no reason not to simply update to the latest version.

**Pull request closed without merging**
