### PR TITLE
Add test for FastDatePrinter.parsePattern and FastDatePrinter.selectNumberRule

### PR DESCRIPTION
**Pull request by lacinoire**
Hey 😊
I want to contribute the following test:

Test that a `java.lang.IllegalArgumentException` is thrown when the parameter `dateStringFormat` of the method `SQLiteConfig.setDateStringFormat` is set to `yyyy/mUm/dd`.
This tests the methods [`FastDatePrinter.parsePattern`](https://github.com/xerial/sqlite-jdbc/blob/ada2b147dc858ef557a995e2f4ef25f7c65fc6a7/src/main/java/org/sqlite/date/FastDatePrinter.java#L155) and [`FastDatePrinter.selectNumberRule`](https://github.com/xerial/sqlite-jdbc/blob/ada2b147dc858ef557a995e2f4ef25f7c65fc6a7/src/main/java/org/sqlite/date/FastDatePrinter.java#L352).
This test is based on the test [`toProperites`](https://github.com/xerial/sqlite-jdbc/blob/ada2b147dc858ef557a995e2f4ef25f7c65fc6a7/src/test/java/org/sqlite/SQLiteConfigTest.java#L12).

Curious to hear what you think!

(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))

### CODE REVIEW

**Comment by gotson** [comment]
@lacinoire can you check the code formatting? 
seems like it's breaking CI

**Comment by lacinoire** [comment]
Hey @gotson !
Thank you for the merge with master. I applied the spotless recommendations 👍🏼
Locally `mvn spotless:check` succeeds now. Could you approve the workflow here to check the CI? 🙂

**Comment by gotson** [comment]
Hi @lacinoire, would you be able to provide more context on this contribution ? Does the format `yyyy/mUm/dd` have a special meaning that would make it required to be tested?

I just had a look at the existing code, and there's no coverage at all for `FastDateFormat`, which would probably be a better point to start (unit tests instead of integration tests).

**Comment by gotson** [comment]
After some more investigation, `FastDateFormat` has been taken from Apache Commons Lang3, and should have sufficient coverage there.

**Comment by gotson** [comment]
I'll be closing this, the PR doesn't bring much value to the test suite.

**Pull request closed without merging**
