### PR TITLE
Modified Makefile to build also for ARM architecture

### PR DESCRIPTION
**Pull request by roedll**
I tried to merge your approach used in the snappy-java project to also crosscompile for ARM and tested the ARM libraries on the BananaPi platform.

Can you please have a look at the changes, if I forgot something...

### CODE REVIEW

**Comment by xerial** [comment]
Please do not use CXX. This is for g++ (CXX_FLAGS). sqlite is compiled with GCC (CC_FLAGS)

**Comment by xerial** [comment]
And changes to Makefile might include newline codes? It's hard to track the differences.

**Comment by roedll** [comment]
I fixed the CXX_FLAGS and reverted them to CC_FLAGS - I didn't know that they were for g++
and unfortunately I wasn't able to fix the newline issue...

**Comment by roedll** [comment]
Finally manage to resolve the line endings issue

**Comment by roedll** [comment]
Added an option to detect armhf in Oracle JDK 8

**Comment by xerial** [comment]
Looks good. Thanks!

**Pull request merged**
