### PR TITLE
refactor: fix typos

### PR DESCRIPTION
**Pull request by bostick**

### CODE REVIEW

**Comment by bostick** [comment]
Any interest in typo fixes?

**Comment by gotson** [comment]
> Any interest in typo fixes?

Yes, but time is scarce to review

**Comment by gotson** [comment]
your changes break code formatting, you can fix it by using `mvn spotless:apply`

**Review by gotson — APPROVED** [review]
LGTM

**Comment by bostick** [comment]
I ran `mvn spotless:apply` and included the 2 spots where it fixed formatting and did a force push.

**Comment by gotson** [comment]
> and did a force push.

please refrain from doing so, it makes the review more difficult, because i don't know what is the delta between my last review

**Comment by gotson** [comment]
@bostick thanks for the PR !

**Pull request merged**
