### PR TITLE
Don't close prepared statements on constraint violation (Fixes #74)

### LINKED ISSUE #74: Prepared statements close/finalize on constraint violations.
Use case:
We are creating a prepared statement outside a loop. Inside the loop we bind the values to each parameter and then execute the prepared statement. The loop is running over data being read from an external source.

Issue:
If the prepared statement has an exception (e.g. constraint violation) the rest of the loop produces "statement is not executing" errors.

Cause:
This is caused by the statement being finalized in DB.java

   execute(CoreStatement stmt, Object[] vals)

when step returns SQLITE_CONSTRAINT.

Workaround:
If an exception is thrown then recreate the prepared statement. This is not ideal as it means you can not easily use lambda's or try with resource.

### PR DESCRIPTION
**Pull request by b3nn0**
Fixes issue #74 .

### CODE REVIEW

**Comment by xerial** [comment]
Merged. Thanks!

**Comment by patricklucas** [comment]
Apologies for commenting on this years-old change, but I ran into a problem upgrading from 3.23.1 to 3.31.1 and traced it here.

In my application, I am catching the `SQLiteException` thrown at the end of this switch statement and looking at its `resultCode` field, matching it against `SQLiteErrorCode.SQLITE_CONSTRAINT_PRIMARYKEY` to see if it represents a primary key uniqueness violation.

However, `SQLiteErrorCode.SQLITE_CONSTRAINT_PRIMARYKEY` is an "extended" error code, meaning when this change truncates the value to the lower byte with `& 0xFF`, the information in the exception is reduced to the basic error code `SQLiteErrorCode.SQLITE_CONSTRAINT`, breaking my error handling.

@b3nn0 / @xerial: Can either of you comment on whether this was intentional/necessary? Since `SQLiteException` supports extended error codes, I would imagine it's more useful to pass the non-truncated result code to it. Basically, my question is, would it be acceptable to change:

```java
        int statusCode = step(stmt.pointer) & 0xFF;
        switch (statusCode) {
```

to

```java
        int statusCode = step(stmt.pointer);
        switch (statusCode & 0xFF) {
```

?

**Comment by b3nn0** [comment]
From my perspective that makes sense, yes. Don't think there is a real reason to truncate the error code for the exception - only for deciding if the statement should be closed.
If you rely on the status code, I think you should just make a pull request with your recommended change.

**Comment by patricklucas** [comment]
Thanks for your input @b3nn0.

**Pull request merged**
