### PR TITLE
Check if pointer is valid before call to reset()

### PR DESCRIPTION
**Pull request by jberkel**
Test case and proposed fix for #164

### CODE REVIEW

**Comment by xerial** [comment]
Nice catch and fix. Thanks!

**Comment by jberkel** [comment]
@xerial You're welcome! I couldn't find any current snapshots, are they still being built?

**Comment by xerial** [comment]
Just uploaded a snapshot here: https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.14.2.2-SNAPSHOT

**Comment by jberkel** [comment]
@xerial thanks. with that snapshot i still get errors, addressed in #169

**Pull request merged**
