### PR TITLE
Add docker based build of armv6 for Raspberry Pi

### PR DESCRIPTION
**Pull request by xerial**
For resolving UnsatisfiedLinkError #58, #141

### CODE REVIEW

**Comment by xerial** [comment]
@gitblit Tried to build Raspberry Pi by using docker. Please merge this PR if you get any success report with this. I don't have Raspberry Pi, so have no way to test it by myself.

**Comment by xerial** [comment]
Binaries for testing this is available from here: https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.14.2-SNAPSHOT/sqlite-jdbc-3.14.2-20160922.165637-1.jar

**Comment by gitblit** [comment]
@xerial Awesome!  Btw, when I committed the update for 3.14.2 it was purely for changes to the build system.  We still need Linux binaries compiled against the older glibc.  I can't recall what base you were using.

**Comment by xerial** [comment]
For linux x86 and X86_64, I'm using an old CentOS 5 (glibc 2.5) for supporting as many versions of Linux as possible since glibc is guaranteed to be backward compatible.

**Comment by xerial** [comment]
@gitblit Actually I found there is no Linux x86(_64) binary difference with the ones I built 6 months ago https://github.com/xerial/sqlite-jdbc/commit/eb8fd076cf29f0a21dd76917587c0c7f5f6c8ede

**Comment by gitblit** [comment]
@xerial How can that be??  Way different SQLite version!

**Comment by xerial** [comment]
@gitblit Actually these native libraries are built against 3.14.2 :)

**Comment by xerial** [comment]
I'm now double checking...

**Comment by xerial** [comment]
It seemed my VMWare's file cache was broken. I pushed the new native libs. Sorry for the confusion

**Comment by xerial** [comment]
Added scripts for building arvm5 (soft float), and armv6 (hardfloat) libs.

**Comment by xerial** [comment]
Got a success report on Raspberry Pi. I'll merge it.

**Pull request merged**
