### PR TITLE
Add ability to add CEROD extention support for sqlite-jdbc. 

### PR DESCRIPTION
**Pull request by opensource4all**
CEROD (Compressed and Encrypted Read-Only Database) is a commercially available SQLite extention.  To integrate CEROD into sqlite-jdbc requires changes to several files in sqlite-jdbc.  For anyone who is a licensee of CEROD, this is a tedious task to have to manually make every time a new release of SQLite is available and an upgrade is needed.
I've enhanced the sqlite-jdbc build system (Makefile, Makefile.common) and the source code (.java and .c) to allow an easy and painless integration of the CEROD extention.
In addition, the changes performed in this release are generic enough that they may further enhance the ability to integrate other extensions.

### CODE REVIEW

**Comment by michael-o** [comment]
I had such requests in other projects as well. I closed all of them because as an OSS developer I do not have any access those productions/extensions to provide some kind of support. Unless you provide a perpertual, non-revocable license of your commercial extension, I'd recommend the sqlite-jdbc devs to close this right away.

**Comment by opensource4all** [comment]
Acknowledged.  
Please give me some time to consider the options available here.

**Comment by gotson** [comment]
> I've enhanced the sqlite-jdbc build system (Makefile, Makefile.common) and the source code (.java and .c) to allow an easy and painless integration of the CEROD extention.
> In addition, the changes performed in this release are generic enough that they may further enhance the ability to integrate other extensions.

The problem is that no 2 extensions will be installed in the same way. I was looking at SEE for another issue, and it's not installed in the same way.

---

I agree with @michael-o, it's complicated to support and it only serves a very limited audience.

It should be fairly simple to have your fork with the necessary changes, so you can keep it in sync with the upstream, and perform your builds as needed.

**Comment by opensource4all** [comment]
I'm closing this pull request.

**Pull request closed without merging**
