### PR TITLE
Add xTrace and xProfile support

### PR DESCRIPTION
**Pull request by gitblit**
This PR exposes the `xTrace` and `xProfile` functionality to Java allowing you to instrument the SQLite engine.

http://www.sqlite.org/c3ref/profile.html

My C is pretty rusty so I'd appreciate a close inspection of the C code.

### CODE REVIEW

**Comment by gitblit** [comment]
Any chance you plan to look into this?

**Comment by xerial** [comment]
ok. I'll look at the build script later.

**Comment by xerial** [comment]
Let me merge it first, then I'll prepare binaries.

**Comment by xerial** [comment]
Ah. Travis build failure forbids merging at GitHub. Need to prepare binaries.

**Comment by xerial** [comment]
@gitblit 
Would you mind if I add you to the contributor of sqlite-jdbc? I'll review the PRs, it would be better if you are able to make changes at any timing.

**Comment by gitblit** [comment]
I don't mind.

Before you merge this you should carefully review the C changes.  I think there is a very subtle glitch but I have not been able to find it.  Any help you could provide would be nice.

**Comment by xerial** [comment]
Thanks. Added you to the contributor list.

It looks like you already updated the binary, but it still shows JVM crash. Maybe accessing a strange memory location.

**Comment by gitblit** [comment]
Actually, @mkauf if you could help review my own PR from 2 years ago that would be helpful.  I've made a mistake in my C code which blows up the test suite - but not when you run the new test class by itself.  Would you will willing to review and offer advice or adjustments?

**Comment by gitblit** [comment]
These functions have been deprecated by upstream.

**Pull request closed without merging**
