### PR TITLE
Add support for HP-UX IA64N

### PR DESCRIPTION
**Pull request by michael-o**
These commits make it flawlessly compile on HP-UX for me. All tests pass.

### CODE REVIEW

**Comment by michael-o** [comment]
Do no yet merge, I am examing the visibility behavior.

**Comment by michael-o** [comment]
It turns out that the `jni_md.h` does not properly handle `JNIEXPORT` also `__attribute__ ((visibility("default"|"protected"|"hidden")))` is available and works. I will inquire with HPE support. The bundled `jni_md.h` will do for now.

**Comment by michael-o** [comment]
OK, for those who will stumble upon this. The issue has been confirmed by the HPE HP-UX JVM team and is slated to be fixed (`jni_md.h`) in either March for June update of the JDK for HP-UX.

**Comment by michael-o** [comment]
The current PR works perfectly on HP-UX and I am able to add 2 000 000 rows in less than 90 s into the database.

**Comment by michael-o** [comment]
@xerial Would you be so kind and have a look and merge?

**Comment by xerial** [comment]
ok. Merged

**Pull request merged**
