### PR TITLE
Check whether the database or prepared statements have been closed

### PR DESCRIPTION
**Pull request by mkauf**
This is a partial fix for https://bitbucket.org/xerial/sqlite-jdbc/issues/122/

The JVM does not crash anymore because of the native code, but the Java code is still not thread-safe.

### CODE REVIEW

**Comment by gitblit** [comment]
@mkauf Would you be willing to cherry-pick & rebase just the commit on checking the database and statements status?  Would also be nice to test these changes too.

**Comment by mkauf** [comment]
I have updated the pull request, but it still depends on #84... I hope #84 gets applied, so this one will fit too.

**Comment by gitblit** [comment]
@mkauf Could you rebase on master?

**Comment by mkauf** [comment]
@gitblit done

**Comment by gitblit** [comment]
:+1: Nice.

**Pull request merged**
