### PR TITLE
Code formatting via Spotless with google java format

### PR DESCRIPTION
**Pull request by gotson**
as discussed here: https://github.com/xerial/sqlite-jdbc/discussions/651

### CODE REVIEW

**Comment by gotson** [comment]
@xerial by binding Spotless to the `compile` phase, the CI running on Ubuntu JDK 8 fails. What do you want to do about it ?

Options I see:
1. drop JDK 8 from CI
2. bind spotless to the `verify` phase, and run a separate CI job to check formatting

The problem with option 2 is that people could very much commit and push code without running spotless, so we would catch the formatting at CI only, making the feedback loop longer.

**Comment by gotson** [comment]
One more solution would be to compile in CI using jdk 11, but run the ci job with jdk8. That would probably mean splitting the job in 2, and store artifacts temporarily.

**Comment by xerial** [comment]
I prefer
> 2. bind spotless to the verify phase, and run a separate CI job to check formatting

**Comment by gotson** [comment]
> I prefer
> 
> > 1. bind spotless to the verify phase, and run a separate CI job to check formatting

I changed it, please have a look when you have time 🙏🏻

**Comment by xerial** [comment]
LGTM. Thanks for fixing the long standing issue :)

**Pull request merged**
