### PR TITLE
update OSInfo.java

### PR DESCRIPTION
**Pull request by ChanthMiao**
* add ppc64el/ppc64le mapping

* recompile OSInfo.class with JDK 1.8

* delete old 'lib/org/sqlite/OSInfo.class'

### CODE REVIEW

**Comment by gotson** [comment]
The class files should not even be here, I think they are not used and should be deleted completely.

**Comment by ChanthMiao** [comment]
> The class files should not even be here, I think they are not used and should be deleted completely.

https://github.com/xerial/sqlite-jdbc/blob/ada2b147dc858ef557a995e2f4ef25f7c65fc6a7/Makefile.common#L20-L24

It seems that the class files are referenced here.

**Comment by gotson** [comment]
Looks like it's used only when `OS_NAME` and `OS_ARCH` are not passed, so probably when using `make native`.

IMHO we should compile osinfo if needed when those variables are not needed, instead of committing them to source control.

**Comment by ChanthMiao** [comment]
You are right. We should not commit class files to git repo

**Comment by ChanthMiao** [comment]
@gotson I just made a new PR https://github.com/xerial/sqlite-jdbc/pull/697, which deleted precompiled OSInfo.class safely.

**Comment by gotson** [comment]
@ChanthMiao looking at the existing code in master, it should work fine.

The only problem is that that class files must have been committed by error.

I would suggest a single PR that deletes the existing class, and adds a `.gitignore` entry to avoid committing again in the future.

Separating your PR about ppc64le in another PR would also make the PR clearer and easier to merge IMHO.

**Comment by ChanthMiao** [comment]
It was not commited by error. The OSInfo.class was commit by https://github.com/xerial/sqlite-jdbc/commit/f09fb1ea13fb5ab17cdda50d64950f040e023eef

Then it Integrated by the other commit https://github.com/xerial/sqlite-jdbc/commit/6d3bfb76b43218753833f25a9674b278a9e10882

**Comment by ChanthMiao** [comment]
> @ChanthMiao looking at the existing code in master, it should work fine.
> 
> The only problem is that that class files must have been committed by error.
> 
> I would suggest a single PR that deletes the existing class, and adds a `.gitignore` entry to avoid committing again in the future.
> 
> Separating your PR about ppc64le in another PR would also make the PR clearer and easier to merge IMHO.

The new PR, which  deletes the existing class is here https://github.com/xerial/sqlite-jdbc/pull/698.

If it merged, I would make ther other one to add ppc64le mapping

**Comment by gotson** [comment]
@ChanthMiao i will merge #715 soon that will handle OSInfo on the fly compilation.

Can you cleanup this PR to keep only the ppc64el/ppc64le mapping ? This should help to close #450

**Comment by ChanthMiao** [comment]
> 

I may do it this weekend.

**Comment by ChanthMiao** [comment]
@gotson Done!

**Pull request merged**
